{{- if .Values.nginx.enabled }}
kind: Ingress
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}

metadata:
  name: grafana-kiosk
  annotations:
    kubernetes.io/tls-acme: {{ default false .Values.grafana.tls | quote }}
    disco: {{ default false .Values.grafana.disco | quote }}
{{- if .Values.ingress.global }}
    disco/zone-name: "global.cloud.sap"
{{- end }}
spec:
  tls:
    - secretName: tls-grafana-kiosk
      hosts: ["{{.Values.nginx.endpoint.host.public}}"]
  rules:
    - host: "{{.Values.nginx.endpoint.host.public}}"
      http:
        paths:
        - path: /
          backend:
            serviceName: grafana
            servicePort: {{.Values.nginx.endpoint.port.public}}
{{- end }}
