{{- if .Values.mariadb_api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-api-db-init
  labels:
    system: openstack
    type: configuration
    component: database
data:
  init.sql: |
    CREATE DATABASE {{ .Values.apidbName }} CHARACTER SET utf8 COLLATE utf8_general_ci;
    GRANT ALL PRIVILEGES ON {{ .Values.apidbName }}.* TO {{ .Values.apidbUser }}@localhost IDENTIFIED BY '{{ .Values.apidbPassword }}';
    GRANT ALL PRIVILEGES ON {{ .Values.apidbName }}.* TO {{ .Values.apidbUser }}@'%' IDENTIFIED BY '{{ .Values.apidbPassword }}';

{{- end }}
