{{- if .Values.mariadb_cell2.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-cell2-db-init
  labels:
    system: openstack
    type: configuration
    component: database
data:
  init.sql: |
    CREATE DATABASE {{ .Values.cell2dbName }} CHARACTER SET utf8 COLLATE utf8_general_ci;
    GRANT ALL PRIVILEGES ON {{ .Values.cell2dbName }}.* TO {{ .Values.cell2dbUser }}@localhost IDENTIFIED BY '{{ .Values.cell2dbPassword }}';
    GRANT ALL PRIVILEGES ON {{ .Values.cell2dbName }}.* TO {{ .Values.cell2dbUser }}@'%' IDENTIFIED BY '{{ .Values.cell2dbPassword }}';

{{- end }}
