{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-mysql-db-init
  labels:
    system: openstack
    type: configuration
    component: database
data:
  init.sql: |
    CREATE DATABASE {{ .Values.dbName }} CHARACTER SET utf8 COLLATE utf8_general_ci;
    GRANT ALL PRIVILEGES ON {{ .Values.dbName }}.* TO {{ .Values.dbUser }}@localhost IDENTIFIED BY '{{ default .Values.dbPassword .Values.global.dbPassword }}';
    GRANT ALL PRIVILEGES ON {{ .Values.dbName }}.* TO {{ .Values.dbUser }}@'%' IDENTIFIED BY '{{ default .Values.dbPassword .Values.global.dbPassword }}';
    CREATE DATABASE {{ .Values.cell0dbName }} CHARACTER SET utf8 COLLATE utf8_general_ci;
    GRANT ALL PRIVILEGES ON {{ .Values.cell0dbName }}.* TO {{ .Values.cell0dbUser }}@localhost IDENTIFIED BY '{{ default .Values.cell0dbPassword .Values.global.dbPassword }}';
    GRANT ALL PRIVILEGES ON {{ .Values.cell0dbName }}.* TO {{ .Values.cell0dbUser }}@'%' IDENTIFIED BY '{{ default .Values.cell0dbPassword .Values.global.dbPassword }}';

{{- end }}
