{{- if .Values.postgresql.postgresPassword }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-db-init
  labels:
    system: openstack
    type: configuration
    component: database
data:
  db-init.sql: |
    SELECT 1;
{{- end }}
