---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-manager-hermes-etc
  namespace: hermes
  labels:
    system: openstack
    service: audit
    component: configuration

data:
  elasticsearch-application.conf: |
{{ include "hermes/templates/etc/_application.conf.tpl" . | indent 4 }}
  logback.xml: |
{{ include "hermes/templates/etc/_logback.xml.tpl" . | indent 4 }}
