apiVersion: v1
kind: Secret

metadata:
  name: prometheus-kubernikus-additional-scrape-config
  labels:
    prometheus: kubernetes

data:
  scrape-config.yaml: {{ tpl .Values.extraScrapeConfig . | b64enc -}}
