{{- if .Values.mariadb.restore.enabled }}
apiVersion: batch/v1
kind: Job
metadata: 
  name: datahubdb-restore
  namespace: datahub
  labels:
    component: datahubdb-restore
    system: openstack
spec:
  template:
    spec:
      containers:
      - name: datahubdb-restore
        image: "{{ .Values.mariadb.restore.image.repo }}:{{ .Values.mariadb.restore.image.tag }}"
        volumeMounts:
        - name: restore-config
          mountPath: /config
      restartPolicy: Never
      volumes:
      - name: restore-config
        configMap:
          name: datahubdb-restore-config
  backoffLimit: 2
{{- end }}