jumpserver:
   enabled: false
   image:
      name: jumphealth
      tag: 1.4
   radius_secret: DEFINED-IN-REGION-SECRETS
   port_number: 9150
   alerts:
      enabled: true
      prometheus: infra-frontend
   region: DEFINED-IN-REGION-SECRETS
global:
   registry: DEFINED-IN-GLOBAL-SECRETS
