dependencies:
  - name: utils
    repository: file://../../openstack/utils
    version: 0.1.1
  - name: mariadb
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.4
    condition: mariadb.enabled
  - name: mysql_metrics
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.3
    condition: mariadb.enabled
  - name: memcached
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.3
  - name: rabbitmq
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.9
  - name: rabbitmq
    alias: rabbitmq_notifications
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.9
  - name: region_check
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2
  - name: jaeger-operator
    repository: file://../../system/jaeger-operator
    version: 0.1.0
    condition: osprofiler.jaeger.enabled
    import-values:
      - child: jaeger
        parent: osprofiler.jaeger
