kubernikus:
  imageTag: 359dec972a03c720fce6c44e89f5cac3e43c99d2
  k8sniff:
    enabled: false #k8sniffer is provided centrally in the admin cluster

  #use a dedicated serviceaccount and proper RBAC rules for this deployment
  standalone: false 
  useServiceAccount: true
  includeRBAC: true

  api:
    policyFile: /etc/kubernikus/policy-ccadmin.json
  operator:
    nodeAffinity: false
    controllers: [groundctl, deorbiter, migration, servicing, certs]
  ingress:
    annotations:
      disco: "true"
