kind: Service
apiVersion: v1
metadata:
  name: ucs-exporter
  namespace: infra-monitoring
spec:
  selector:
    app: ucs-exporter
  ports:
    - name: metrics
      port: {{ .Values.ucs.port_number }}
