{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ template "blackbox-exporter.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}

spec:
  revisionHistoryLimit: 5
  replicas: {{ required ".Values.replicaCount missing" .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "blackbox-exporter.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "blackbox-exporter.name" . }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: {{ required ".Values.service.port missing" .Values.service.port | quote }}
        prometheus.io/targets: "kubernetes,openstack"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ required ".Values.image.repository missing" .Values.image.repository }}:{{ required ".Values.image.tag missing" .Values.image.tag }}
          imagePullPolicy: {{ required ".Values.image.pullPolicy missing" .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ required ".Values.service.port missing" .Values.service.port }}
          args:
            - --config.file=/etc/blackbox-exporter/blackbox.yaml
            - --web.external-url={{ include "hostname" . }}
            - --web.route-prefix=/
            - --web.listen-address=0.0.0.0:{{ required ".Values.service.port missing" .Values.service.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox-exporter
        - name: {{ .Chart.Name }}-configmap-reloader
          image: {{ required ".Values.configmapReload.image.repository missing" .Values.configmapReload.image.repository }}:{{ required ".Values.configmapReload.image.tag missing" .Values.configmapReload.image.tag }}
          args:
            - --volume-dir=/etc/blackbox-exporter
            - --webhook-url=http://localhost:{{ required ".Values.service.port missing" .Values.service.port }}/-/reload
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox-exporter
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}
